# wrangler.toml
compatibility_date = "2026-06-15"
compatibility_flags = ["nodejs_compat"]

# Important for next-on-pages
pages_build_output_dir = ".vercel/output/static"

name = "phalo-transportation"